packaging_format = 2

id = "duniter"
name = "duniter-v2s"
description.en = "Crypto-currency software (based on Substrate framework) to operate Ğ1 libre currency"
description.fr = "Logiciel de crypto-monnaie (basé sur le framework Substrate) pour utiliser la monnaie libre Ğ1."

version = "1.0~ynh1"

maintainers = ["Axiom-Team"]

[upstream]
license = "AGPL-3.0"
website = "https://duniter.org"
code = "https://git.duniter.org/nodes/rust/duniter-v2s"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false

ldap = false
sso = false

disk = "1000M"
ram.build = "1000M"
ram.runtime = "500M"

[install]

    [install.domain]
    type = "domain"

    [install.node_name]
    help.en = "Node name?"
    help.fr = "Nom du nœud ?"
    type = "string"

    [install.node_type]
    help.en = "Type of node?"
    help.fr = "Type de nœud ?"
    type = "string"
    default = "mirror"
    choice.mirror = "mirror"
    choice.smith = "smith"

    [install.node_listen_addr]
    help.en = "Address and port for node communication. If SMITH NODE: `/ip4/0.0.0.0/tcp/<port>` and `/ip6/[::]/tcp/<port>`. Otherwise: `/ip4/0.0.0.0/tcp/<port>/ws` and `/ip6/[::]/tcp/<port>/ws`."
    help.fr = "Adresse et port pour la communication du nœud. Si SMITH : /ip4/0.0.0.0/tcp/<port> et /ip6/[::]/tcp/<port>. Sinon : /ip4/0.0.0.0/tcp/<port>/ws et /ip6/[::]/tcp/<port>/ws."
    type = "string"
    default = "/ip4/0.0.0.0/tcp/30333"

[resources]
    [resources.sources]

    [resources.sources.main]
    url = "https://git.duniter.org/nodes/rust/duniter-v2s/-/archive/fix-200/duniter-v2s-fix-200.tar.gz" #TODO for dev
    sha256 = "d52f3fcd83c70f14392c75d5846fc61211e9b373d5b42d86f0002d2d1a71f921"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]

    [resources.ports]
    main.default = 9944

    [resources.apt]
    packages = "build-essential, clang, git, cmake, protobuf-compiler, libssl-dev, curl, openssl, libudev-dev, curl, llvm"
