#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info --message="Declaring files to be backed up..."

export $(grep -v '^#' /etc/duniter/env_file | xargs -d '\n')
ynh_backup --src_path="${BASE_PATH}" --is_big

ynh_backup --src_path="/etc/$app/"

ynh_backup --src_path="/var/log/$app/"

ynh_print_info --message="Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
