#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info --message="Declaring files to be backed up..."

# Backup the nginx configuration
ynh_backup --src_path="/etc/nginx/conf.d/$domain.d/$app.conf"

export $(grep -v '^#' /etc/duniter/env_file | xargs -d '\n')
ynh_backup --src_path="${BASE_PATH}" --is_big

ynh_backup --src_path="/etc/$app/"


if [ $node_type = "mirror" ]; then
    ynh_backup --src_path="/etc/systemd/system/duniter-mirror.service"
else
    ynh_backup --src_path="/etc/systemd/system/duniter-smith.service"
    ynh_backup --src_path="/etc/systemd/system/distance-oracle.service"
    ynh_backup --src_path="/etc/systemd/system/distance-oracle.timer"
fi

ynh_backup --src_path="/var/log/$app/"

ynh_print_info --message="Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
