#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Stopping $app's systemd service..." --weight=1

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if [ $node_type = "mirror" ]; then
    ynh_systemd_action --service_name="duniter-mirror" --action="stop" --line_match="Stop" --log_path="systemd"
else
    ynh_systemd_action --service_name="duniter-smith" --action="stop" --line_match="Stop" --log_path="systemd"
    ynh_systemd_action --service_name="distance-oracle.timer" --action="stop" --line_match="Stop" --log_path="systemd"
fi

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression --message="Updating NGINX web server configuration..." --weight=1

ynh_change_url_nginx_config

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting $app's systemd service..." --weight=1

if [ $node_type = "mirror" ]; then
    ynh_systemd_action --service_name="duniter-mirror" --action="start" --line_match="Started" --log_path="systemd"
else
    ynh_systemd_action --service_name="duniter-smith" --action="start" --line_match="Started" --log_path="systemd"
    ynh_systemd_action --service_name="distance-oracle.timer" --action="start" --line_match="Started" --log_path="systemd"
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Change of URL completed for $app" --last
