#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1
# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"


#=================================================
# INSTALLATION
#=================================================
ynh_script_progression --message="Installing $app..." --weight=1

ynh_add_nginx_config

dpkg -i ${install_dir}/duniter*.deb

# Force duniter home permission
chown -R duniter:duniter /home/duniter
chmod 700 /home/duniter

# Update config file
sed -i "s/DUNITER_NODE_NAME.*/DUNITER_NODE_NAME=$node_name/g" "/etc/duniter/env_file"
sed -i "s/DUNITER_LISTEN_ADDR.*/DUNITER_LISTEN_ADDR=${node_listen_addr//\//\\/}/g" "/etc/duniter/env_file"

# Generate the node keys
export $(grep -v '^#' /etc/duniter/env_file | xargs -d '\n')
su -s /bin/bash -c "duniter2 key generate-node-key --base-path ${BASE_PATH} --chain ${DUNITER_CHAIN_NAME}" duniter

# Use logrotate to manage application logfile(s)
ynh_use_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting systemd services..." --weight=1

if [ $node_type = "mirror" ]; then
    ynh_systemd_action --service_name="duniter-mirror" --action="start" --line_match="Started" --log_path="systemd"
else
    ynh_systemd_action --service_name="duniter-smith" --action="start" --line_match="Started" --log_path="systemd"
    ynh_systemd_action --service_name="distance-oracle.timer" --action="start" --line_match="Started" --log_path="systemd"
fi


#=================================================
# CLEAN
#=================================================
ynh_script_progression --message="Cleaning..." --weight=1
ynh_secure_remove --file="$install_dir/"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
