#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

### Settings are automatically loaded as bash variables
### in every app script context, therefore typically these will exist:
### - $domain
### - $path
### - $language
### - $install_dir
### - $port
### ...

### For remove operations :
### - the core will deprovision every resource defined in the manifest **after** this script is ran
### this includes removing the install directory, and data directory (if --purge was used)

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

### This should be a symetric version of what happens in the install script

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if [ $node_type = "mirror" ]; then
    ynh_remove_systemd_config --service="duniter-mirror"
else
    ynh_remove_systemd_config --service="duniter-smith"
    ynh_systemd_action --service_name="distance-oracle.timer" --action="stop" --line_match="Stop" --log_path="systemd"
    ynh_secure_remove --file="/etc/systemd/system/distance-oracle.timer"
    ynh_remove_systemd_config --service="distance-oracle"
fi

# Remove other various files specific to the app... such as :

export $(grep -v '^#' /etc/duniter/env_file | xargs -d '\n')
ynh_secure_remove --file="${BASE_PATH}"

ynh_secure_remove --file="/etc/$app"

ynh_secure_remove --file="/var/log/$app"

ynh_secure_remove --file="/usr/bin/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
