#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

if [ $node_type = "mirror" ]; then
    ynh_systemd_action --service_name="duniter-mirror" --action="stop" --line_match="Stopped" --log_path="systemd"
else
    ynh_systemd_action --service_name="duniter-smith" --action="stop" --line_match="Stopped" --log_path="systemd"
    ynh_systemd_action --service_name="distance-oracle.timer" --action="stop" --line_match="Stopped" --log_path="systemd"
fi

export $(grep -v '^#' /etc/duniter/env_file | xargs -d '\n')

ynh_secure_remove --file="${BASE_PATH}"

dpkg --purge duniter


#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
