#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE VARIOUS FILES
#=================================================
ynh_script_progression --message="Restoring various files..." --weight=1

ynh_restore_file --origin_path="/etc/$app/"

ynh_restore_file --origin_path="/var/log/$app/"

export $(grep -v '^#' /etc/duniter/env_file | xargs -d '\n')
ynh_restore_file --origin_path="${BASE_PATH}"


#=================================================
# RESTORE SYSTEMD CONFIGURATIONS
#=================================================
ynh_script_progression --message="Restoring system configurations related to $app..." --weight=1

getent group duniter >/dev/null 2>&1 || addgroup --system "duniter"
getent passwd duniter >/dev/null 2>&1 || adduser --system --disabled-password --ingroup "duniter" "duniter"

if [ $node_type = "mirror" ]; then
    ynh_restore_file --origin_path="/etc/systemd/system/duniter-mirror.service"
    systemctl enable "duniter-mirror.service" --quiet
else
    ynh_restore_file --origin_path="/etc/systemd/system/duniter-smith.service"
    systemctl enable "duniter-mirror.service" --quiet
    ynh_restore_file --origin_path="/etc/systemd/system/distance-oracle.service"
    ynh_restore_file --origin_path="/etc/systemd/system/distance-oracle.timer"
    systemctl enable "distance-oracle.timer" --quiet
fi

ynh_restore_file --origin_path="/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_script_progression --message="Reloading NGINX web server and $app's service..." --weight=1
ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=1

if [ $node_type = "mirror" ]; then
    ynh_systemd_action --service_name="duniter-mirror" --action="start" --line_match="Started" --log_path="systemd"
else
    ynh_systemd_action --service_name="duniter-smith" --action="start" --line_match="Started" --log_path="systemd"
    ynh_systemd_action --service_name="distance-oracle.timer" --action="start" --line_match="Started" --log_path="systemd"
fi

#=================================================
# GENERIC FINALIZATION
#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Restoration completed for $app" --last
