#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD UPGRADE STEPS
#=================================================
ynh_script_progression --message="Stopping systemd services..." --weight=1

if [ $node_type = "mirror" ]; then
    ynh_systemd_action --service_name="duniter-mirror.service" --action="stop" --line_match="Stopped" --log_path="systemd"
else
    ynh_systemd_action --service_name="duniter-smith.service" --action="stop" --line_match="Stopped" --log_path="systemd"
    ynh_systemd_action --service_name="distance-oracle.timer" --action="stop" --line_match="Stopped" --log_path="systemd"
fi

ynh_script_progression --message="Upgrading $app..." --weight=1

ynh_setup_source --dest_dir="$install_dir"

chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R "duniter:duniter" "$install_dir"

dpkg -i ${install_dir}/duniter*.deb

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Upgrading system configurations related to $app..." --weight=1

# Use logrotate to manage application logfile(s)
ynh_use_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting systemd services..." --weight=1

if [ $node_type = "mirror" ]; then
    ynh_systemd_action --service_name="duniter-mirror" --action="start" --line_match="Started" --log_path="systemd"
else
    ynh_systemd_action --service_name="duniter-smith" --action="start" --line_match="Started" --log_path="systemd"
    ynh_systemd_action --service_name="distance-oracle.timer" --action="start" --line_match="Started" --log_path="systemd"
fi

#=================================================
# CLEAN
#=================================================
ynh_script_progression --message="Cleaning..." --weight=1
ynh_secure_remove --file="$install_dir/"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
